// generated by mBlock5 for MegaPi
// codes make you happy

#include <Arduino.h>
#include <Wire.h>
#include <MeMegaPi.h>

MeEncoderOnBoard Encoder_1(SLOT1);

void setup(){

}


void loop(){
  Encoder_1.runSpeed(300);

}